on: push

jobs:
  test_and_compile:
    runs-on: ubuntu-latest
    name: test and compile
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pandoc lmodern wkhtmltopdf

      - name: Run tests
        run: make test

      - name: Build
        run: make

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/
